---
title: reproduce the DESeq2 analysis for the Pasilla data
author: Bin He
date: 2022-11-05
output: html_notebook
---

reference: https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html

## install libraries
```{r}
installed_packages <- rownames(installed.packages())
if(!require("tidyverse", quietly = TRUE))
  install.packages("tidyverse")

if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

if (!require("DESeq2", quietly = TRUE))
  BiocManager::install("DESeq2", lib = .libPaths()[1])

if (!require("pasilla", quietly = TRUE))
  BiocManager::install("pasilla", lib = .libPaths()[1])
# load libraries
require(tidyverse)
require(DESeq2)
require(pasilla)
```

## Input count matrix
Read count data from `pasilla` package
```{r}
library("pasilla")
pasCts <- system.file("extdata",
                      "pasilla_gene_counts.tsv",
                      package="pasilla", mustWork=TRUE)
pasAnno <- system.file("extdata",
                       "pasilla_sample_annotation.csv",
                       package="pasilla", mustWork=TRUE)
cts <- as.matrix(read.csv(pasCts,sep="\t",row.names="gene_id"))
coldata <- read.csv(pasAnno, row.names=1)
coldata <- coldata[,c("condition","type")]
coldata$condition <- factor(coldata$condition)
coldata$type <- factor(coldata$type)
```

Rename and reorder the count matrix rows to be consistent with the `coldata`
```{r}
rownames(coldata) <- sub("fb", "", rownames(coldata))
cts <- cts[, rownames(coldata)]
all(rownames(coldata) %in% colnames(cts))
all(rownames(coldata) == colnames(cts))
```

Construct a DESeqDataSet
```{r}
dds <- DESeqDataSetFromMatrix(countData = cts,
                              colData = coldata,
                              design = ~ condition)
dds
```

## Pre-filtering and setting the reference level
```{r}
#keep <- rowSums(counts(dds)) >= 10
#dds <- dds[keep,]
#dds
```

```{r}
dds$condition <- relevel(dds$condition, ref = "untreated")
```

## Diifferential expression analysis
```{r}
dds <- DESeq(dds)
res <- results(dds)
res
```

Compare the `DESeq2` in R results with the Galaxy results
```{r}
dat <- read_tsv("DESeq2-result-with-NA.txt", 
                col_names = c("GeneID","Base mean","log2(FC)","StdErr","Wald-Stats","P-value","P-adj","Chromosome","Start","End","Strand","Feature","Gene name"), 
                col_types = cols())
dt1 <- tibble(GeneID = rownames(res), pval1 = res$pvalue, padj1 = res$padj)
comp <- left_join(dt1, select(dat, GeneID, pval2 = `P-value`, padj2 = `P-adj`), by = "GeneID")
comp
```

```{r}
comp %>% 
  filter(!is.na(pval1), !is.na(pval2), pval1 != 0, pval2 != 0) %>% 
  ggplot(aes(x = pval1, y = pval2)) + geom_point() + 
  stat_smooth(method = "lm", formula = y~x)
comp %>% 
  filter(!is.na(padj1), !is.na(padj2), padj1 != 0, padj2 != 0) %>% 
  ggplot(aes(x = padj1, y = padj2)) + geom_point() + 
  stat_smooth(method = "lm", formula = y~x)

```

